
  - name: 'Install epel-release yum'
    ansible.builtin.yum:
     name:
      - epel-release
     state: latest
     update_cache: yes  
 
 

 
  - name: 'Install nginx yum'
    ansible.builtin.yum:
     name:
      - epel-release
      - nginx
     state: latest
     update_cache: yes  
     
     
  - name: 'update html folder permissions'
    ansible.builtin.file:
     path: "/usr/share/nginx/html"
     state: directory
     owner: "vagrant"
     group: "vagrant"


  - name: Delete /var/www/html folder
    ansible.builtin.file:
     state: "absent"
     path: "/usr/share/nginx/html"
     

 
  - name: 'copy our lending to /var/www/html folder'
    ansible.builtin.copy:
     src: "files/html"
     dest: "/usr/share/nginx/" 
     owner: "vagrant"
     group: "vagrant"
     mode: "0644" 

  - name: 'copy config file'
    ansible.builtin.template:
     src: "nginx.centos.conf.j2"
     dest: "/etc/nginx/conf.d/default.conf" 
     owner: "vagrant"
     group: "vagrant"
     mode: "0644"  
